name: social-blogging

volumes:
  social-blogging:

services:
  mongo:
    image: mongo
    volumes:
      - social-blogging:/data/db
  social-blogging:
    build: 
      context: .
      args:
        - VERSION=0.0.1
    ports:
      - "8080:8080"
    links:
      - mongo
