version: '3'

services:
  blog:
    image: nginx:alpine
    volumes:
      - ./blog/content:/usr/share/nginx/html
      - ./blog/config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - social-blogging
    ports:
      - "8080:80"
  social-blogging:
    build: ../
    ports:
      - "3000:3000"
