name: Build Container Candidate

on:
  push:
    branches: [ main ]

env:
  CONTAINER_IMAGE: ghcr.io/snscaimito/social-blogging:candidate

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
        cache: 'maven'

    - name: Build with Maven
      run: ./mvnw package

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.CONTAINER_IMAGE }}
